/**
 * Render worker. Runs under Node (not Bun): @remotion/renderer drives a headless Chrome and
 * its own compositor binary, which are only supported on Node. Emits NDJSON events on stdout.
 *
 *   node packages/render/src/worker.ts --job /tmp/job.json
 */
import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, open, readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { bundle } from '@remotion/bundler';
import { makeCancelSignal, openBrowser, renderMedia, renderStill, selectComposition, type CancelSignal } from '@remotion/renderer';
import { projectDurationFrames } from '@neon/core';
import type { RenderJobSpec, WorkerEvent } from './types.ts';

type Job<K extends RenderJobSpec['kind']> = Extract<RenderJobSpec, { kind: K }>;
type Size = { width: number; height: number };

const TIMELINE_COMPOSITION_ID = 'Timeline';
const SHEET_COMPOSITION_ID = 'ContactSheet';

type WorkerEventBody = { [K in WorkerEvent['type']]: Omit<Extract<WorkerEvent, { type: K }>, 'neon'> }[WorkerEvent['type']];

function emit(event: WorkerEventBody): void {
  process.stdout.write(`${JSON.stringify({ neon: 1, ...event })}\n`);
}

async function fingerprint(dirs: string[], extra: string): Promise<string> {
  const hash = createHash('sha256');
  hash.update(extra);
  for (const dir of dirs) {
    if (!existsSync(dir)) continue;
    const entries = await readdir(dir, { recursive: true, withFileTypes: true });
    const files = entries
      .filter((e) => e.isFile() && !e.name.endsWith('.test.ts'))
      .map((e) => join(e.parentPath ?? (e as unknown as { path: string }).path, e.name))
      .sort();
    for (const file of files) {
      const s = await stat(file);
      hash.update(`${relative(dir, file)}:${s.size}:${Math.floor(s.mtimeMs)}\n`);
    }
  }
  return hash.digest('hex').slice(0, 16);
}

async function remotionVersion(): Promise<string> {
  try {
    const require = (await import('node:module')).createRequire(import.meta.url);
    const pkg = require('remotion/package.json') as { version: string };
    return pkg.version;
  } catch {
    return 'unknown';
  }
}

/** node_modules directories from `dir` upwards — lets files outside the repo (installed packs) resolve the workspace's react/remotion. */
function nodeModulesAbove(dir: string): string[] {
  const out: string[] = [];
  let current = dir;
  for (let i = 0; i < 12; i++) {
    const candidate = join(current, 'node_modules');
    if (existsSync(candidate)) out.push(candidate);
    const parent = dirname(current);
    if (parent === current) break;
    current = parent;
  }
  return out;
}

/**
 * With installed packs, the bundle entry is a generated module that imports each pack's
 * components and registers them with the workspace before the real entry registers the root.
 */
async function resolveEntry(spec: RenderJobSpec, key: string): Promise<string> {
  const packs = spec.packs ?? [];
  if (packs.length === 0) return spec.entryPoint;
  const templatesIndex = join(dirname(spec.entryPoint), 'templates/index.ts');
  const lines = [
    '// generated by @neon/render — do not edit',
    `import { registerRuntimeComponents } from ${JSON.stringify(templatesIndex)};`,
    ...packs.map((p, i) => `import * as pack${i} from ${JSON.stringify(p.entry)};`),
    `import ${JSON.stringify(spec.entryPoint)};`,
    ...packs.map((p, i) => `registerRuntimeComponents(${JSON.stringify(p.name)}, pack${i} as unknown as Record<string, unknown>);`),
    '',
  ];
  const dir = join(spec.bundleCacheDir, 'entries');
  await mkdir(dir, { recursive: true });
  const file = join(dir, `${key}.ts`);
  await writeFile(file, lines.join('\n'));
  return file;
}

async function ensureBundle(spec: RenderJobSpec): Promise<string> {
  const packs = spec.packs ?? [];
  const key = await fingerprint(spec.watchDirs, `${await remotionVersion()}|${packs.map((p) => `${p.name}@${p.entry}`).join(',')}`);
  const outDir = join(spec.bundleCacheDir, key);
  if (existsSync(join(outDir, 'index.html'))) {
    emit({ type: 'bundle', cached: true, location: outDir });
    return outDir;
  }
  emit({ type: 'stage', stage: 'bundling', message: `Bundling Remotion project${packs.length ? ` + ${packs.length} FX pack${packs.length === 1 ? '' : 's'}` : ''} (first run can take a while)` });
  await mkdir(spec.bundleCacheDir, { recursive: true });
  const entryPoint = await resolveEntry(spec, key);
  const modules = nodeModulesAbove(dirname(spec.entryPoint));
  const location = await bundle({
    entryPoint,
    outDir,
    // The generated pack entry imports the real entry (which calls registerRoot) instead of calling it itself.
    ignoreRegisterRootWarning: packs.length > 0,
    // Keep webpack's persistent cache next to the bundles so re-bundles are fast.
    enableCaching: true,
    webpackOverride: (config) => {
      if (packs.length === 0) return config;
      // Pack sources live outside the workspace tree; resolve their bare imports (react, remotion,
      // @neon/fx-kit…) from the workspace's node_modules so there is exactly one copy of each.
      return { ...config, resolve: { ...config.resolve, modules: [...modules, ...((config.resolve?.modules as string[] | undefined) ?? ['node_modules'])] } };
    },
  });
  emit({ type: 'bundle', cached: false, location });
  return location;
}

async function renderVideo(spec: Job<'video'>, serveUrl: string, cancelSignal: CancelSignal): Promise<Size> {
  const projectFps = spec.project.meta.fps;
  const inputProps = {
    project: spec.project,
    assetBaseUrl: spec.assetBaseUrl,
    assetQuery: spec.assetQuery ?? '',
    render: { width: spec.preset.width, height: spec.preset.height, fps: spec.preset.fps },
  };

  emit({ type: 'stage', stage: 'rendering', message: 'Resolving composition' });
  const composition = await selectComposition({
    serveUrl,
    id: TIMELINE_COMPOSITION_ID,
    inputProps,
    logLevel: 'warn',
    binariesDirectory: spec.binariesDirectory ?? null,
  });

  const scale = composition.fps / projectFps;
  let frameRange: [number, number] | null = null;
  if (spec.frameRange) {
    const total = Math.max(1, Math.round(projectDurationFrames(spec.project) * scale));
    const from = Math.max(0, Math.min(total - 1, Math.round(spec.frameRange[0] * scale)));
    const to = Math.max(from, Math.min(total - 1, Math.round(spec.frameRange[1] * scale)));
    frameRange = [from, to];
  }
  const totalFrames = frameRange ? frameRange[1] - frameRange[0] + 1 : composition.durationInFrames;
  emit({ type: 'start', totalFrames, width: composition.width, height: composition.height, fps: composition.fps });

  await mkdir(dirname(spec.outputPath), { recursive: true });
  await renderMedia({
    composition,
    serveUrl,
    codec: 'h264',
    crf: spec.preset.crf,
    outputLocation: spec.outputPath,
    inputProps,
    frameRange,
    cancelSignal,
    concurrency: spec.concurrency ?? null,
    overwrite: true,
    logLevel: 'warn',
    browserExecutable: spec.browserExecutable ?? null,
    binariesDirectory: spec.binariesDirectory ?? null,
    ...(spec.licenseKey ? { licenseKey: spec.licenseKey } : {}),
    onProgress: ({ progress, renderedFrames, encodedFrames }) => {
      emit({ type: 'progress', progress, renderedFrames, encodedFrames });
    },
  });
  return { width: composition.width, height: composition.height };
}

/** Width and height from a PNG's IHDR chunk. */
async function pngSize(path: string): Promise<Size> {
  const file = await open(path, 'r');
  try {
    const { buffer } = await file.read(Buffer.alloc(24), 0, 24, 0);
    return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
  } finally {
    await file.close();
  }
}

/**
 * A still renders the Timeline at project size and lets Chrome scale the screenshot, so text and
 * FX keep their proportions. A sheet renders the ContactSheet composition at frame 0.
 */
async function renderPng(spec: Job<'still' | 'sheet'>, serveUrl: string, cancelSignal: CancelSignal): Promise<Size> {
  const timeline = { project: spec.project, assetBaseUrl: spec.assetBaseUrl, assetQuery: spec.assetQuery ?? '', render: null };
  const shot =
    spec.kind === 'still'
      ? { id: TIMELINE_COMPOSITION_ID, inputProps: timeline, frame: spec.frame, scale: spec.width / spec.project.meta.width, cells: 1 }
      : { id: SHEET_COMPOSITION_ID, inputProps: { timeline, frames: spec.frames, cols: spec.cols, width: spec.width }, frame: 0, scale: 1, cells: spec.frames.length };

  // One browser for both calls instead of one each.
  const browser = await openBrowser('chrome', { browserExecutable: spec.browserExecutable ?? null, logLevel: 'warn' });
  try {
    emit({ type: 'stage', stage: 'rendering', message: 'Resolving composition' });
    const composition = await selectComposition({
      serveUrl,
      id: shot.id,
      inputProps: shot.inputProps,
      puppeteerInstance: browser,
      logLevel: 'warn',
      binariesDirectory: spec.binariesDirectory ?? null,
    });
    emit({ type: 'start', totalFrames: shot.cells, width: composition.width, height: composition.height, fps: composition.fps });
    await mkdir(dirname(spec.outputPath), { recursive: true });
    await renderStill({
      composition,
      serveUrl,
      output: spec.outputPath,
      frame: shot.frame,
      inputProps: shot.inputProps,
      imageFormat: 'png',
      scale: shot.scale,
      puppeteerInstance: browser,
      cancelSignal,
      overwrite: true,
      logLevel: 'warn',
      binariesDirectory: spec.binariesDirectory ?? null,
      ...(spec.licenseKey ? { licenseKey: spec.licenseKey } : {}),
    });
    emit({ type: 'progress', progress: 1, renderedFrames: shot.cells, encodedFrames: shot.cells });
  } finally {
    await browser.close({ silent: true });
  }
  return pngSize(spec.outputPath);
}

async function main(): Promise<void> {
  const jobIndex = process.argv.indexOf('--job');
  const jobPath = jobIndex >= 0 ? process.argv[jobIndex + 1] : undefined;
  if (!jobPath) throw new Error('Usage: worker.ts --job <spec.json>');
  const spec = JSON.parse(await readFile(jobPath, 'utf8')) as RenderJobSpec;

  const started = Date.now();
  const { cancelSignal, cancel } = makeCancelSignal();
  const onTerminate = () => {
    emit({ type: 'stage', stage: 'rendering', message: 'Cancelling…' });
    cancel();
  };
  process.on('SIGTERM', onTerminate);
  process.on('SIGINT', onTerminate);

  const serveUrl = await ensureBundle(spec);

  let size: Size;
  switch (spec.kind) {
    case 'video':
      size = await renderVideo(spec, serveUrl, cancelSignal);
      break;
    case 'still':
    case 'sheet':
      size = await renderPng(spec, serveUrl, cancelSignal);
      break;
    default: {
      const unreachable: never = spec;
      throw new Error(`Unknown job kind ${JSON.stringify(unreachable)}`);
    }
  }

  emit({ type: 'done', outputPath: spec.outputPath, durationMs: Date.now() - started, ...size });
}

main().then(
  () => process.exit(0),
  (err: unknown) => {
    const e = err instanceof Error ? err : new Error(String(err));
    emit({ type: 'error', message: e.message, stack: e.stack });
    process.exit(1);
  },
);
